"""Add default_cv and default_cover_letter to User

Revision ID: 1261ee601e77
Revises: 62bbbc318311
Create Date: 2025-07-04 12:50:56.411942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1261ee601e77'
down_revision = '62bbbc318311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('review')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('cover_letter_filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_cv', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('default_cover_letter', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('default_cover_letter')
        batch_op.drop_column('default_cv')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('is_public')
        batch_op.drop_column('cover_letter_filename')
        batch_op.drop_column('cv_filename')

    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('reviewer_username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('application_review')
    # ### end Alembic commands ###
