"""Add company column

Revision ID: 62bbbc318311
Revises: 
Create Date: 2025-07-04 12:22:19.896494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bbbc318311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('skill_required',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('application_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reviewer_username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('reviewer_username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('application_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('skill_required',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('company')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
